version: "3.3"
services:
    nodeserver:
        build:
            context: ./simple-website-with-blog
        ports:
            - "3000:3000"
    nginx:
        image: nginx:latest
        restart: always
        ports:
          - "80:80"
        volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf